language: generic

matrix:
  include:
    # Clang
    - os: linux
      env: COMPILER_NAME=clang CC=clang CXX=clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    # GCC 4.9
    - os: linux
      env: COMPILER_NAME=g++ CC=gcc-4.9 CXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

    # GCC 7
    - os: linux
      env: COMPILER_NAME=g++ CC=gcc-7 CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

script:
  - git clone https://github.com/KhronosGroup/SPIRV-Headers
  - wget https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip
  - unzip SPIRV-Tools-master-linux-RelWithDebInfo.zip -d SPIRV-Tools
  - cmake . -DSPIRV_INCLUDE_DIR=$PWD/SPIRV-Headers/include
            -DSPIRV_TOOLS_INCLUDE_DIR=$PWD/SPIRV-Tools/include
            -DSPIRV_TOOLS_LIBRARY_DIR=$PWD/SPIRV-Tools/lib
  - make -j 2
  - ctest . --output-on-failure
